"""
Gradio Web Interface
--------------------
This is the front-end of our application — the page users interact with.

We use Gradio because:
  - It's pure Python (no HTML/CSS/JS needed)
  - Builds a clean web UI with just a few lines
  - You already used it in your original project!

The UI has two tabs:
  Tab 1 — Job Search: user fills in their details, crew runs, report appears
  Tab 2 — About:      explains the project architecture for the assignment
"""

import gradio as gr
from crew import run_job_search_crew
from monitoring.langfuse_config import get_monitoring_status


# ------------------------------------------------------------------ #
# Helper: format the final report nicely for display
# ------------------------------------------------------------------ #
def format_output(result: str) -> str:
    """Adds a header and footer to the crew's output for display."""
    return f"""# 🎯 Your Personalised Job Search Report

{result}

---
*Generated by Job Search CrewAI — powered by GPT-4o-mini, Tavily & Remotive*
"""


# ------------------------------------------------------------------ #
# Main function: called when user clicks "Run Job Search"
# ------------------------------------------------------------------ #
def run_search(job_title, location, candidate_profile, job_description):
    """
    Validates inputs, runs the crew, and returns the result for display.
    This function is wired to the Gradio button click event below.
    """

    # Input validation (fallback before even calling the crew)
    if not job_title.strip():
        return "⚠️ Please enter a job title before running the search."

    if not candidate_profile.strip():
        return "⚠️ Please enter your skills/experience so the Career Advisor can score your fit."

    if len(candidate_profile.strip()) < 30:
        return "⚠️ Your candidate profile is too short. Please add more detail about your skills and experience."

    # Build the user inputs dict (passed to crew.py → tasks.py)
    user_inputs = {
        "job_title": job_title.strip(),
        "location": location.strip() if location.strip() else "Remote",
        "candidate_profile": candidate_profile.strip(),
        "job_description": job_description.strip() if job_description.strip() else "Not provided",
    }

    # Show a status message while running
    yield "⏳ **Running your job search crew... This takes 1-2 minutes.**\n\nHere's what's happening:\n1. 🔍 Job Researcher is searching for listings...\n2. 💰 Salary Analyst is looking up compensation data...\n3. 📋 Job Analyst is summarizing the job description...\n4. 🎯 Career Advisor is scoring your profile fit...\n\nPlease wait..."

    # Run the crew
    result = run_job_search_crew(user_inputs)

    # Yield the final formatted result
    yield format_output(result)


# ------------------------------------------------------------------ #
# Build the Gradio UI
# ------------------------------------------------------------------ #
def build_ui():

    monitoring = get_monitoring_status()
    monitoring_badge = "📊 Monitoring: ON" if monitoring["enabled"] else "📊 Monitoring: OFF (set Langfuse keys)"

    with gr.Blocks(
        title="Job Search CrewAI Assistant",
        theme=gr.themes.Soft(),
    ) as demo:

        # Header
        gr.Markdown("""
# 🤖 Job Search CrewAI Assistant
### A multi-agent AI system that finds jobs, researches salaries, and scores your profile fit

*Built with CrewAI · GPT-4o-mini · Tavily · Remotive · Langfuse*
""")

        gr.Markdown(f"`{monitoring_badge}`")

        # ---- TAB 1: Job Search ---- #
        with gr.Tab("🔍 Job Search"):

            gr.Markdown("""
### How it works
Fill in the fields below and click **Run Job Search**. Four AI agents will collaborate:
1. **Job Researcher** — finds live job listings
2. **Salary Analyst** — researches compensation benchmarks
3. **Job Analyst** — summarizes the job description you paste
4. **Career Advisor** — scores your fit and gives recommendations
""")

            with gr.Row():
                with gr.Column(scale=1):
                    job_title = gr.Textbox(
                        label="Job Title *",
                        placeholder="e.g. Data Scientist, Backend Developer, Product Manager",
                        value="Data Scientist",
                    )
                    location = gr.Textbox(
                        label="Location / Work Type",
                        placeholder="e.g. Malaysia, Singapore, Remote, London",
                        value="Remote",
                    )

            candidate_profile = gr.Textbox(
                label="Your Skills & Experience (Candidate Profile) *",
                placeholder=(
                    "Describe your background, key skills, years of experience, "
                    "education, and any relevant projects.\n\n"
                    "Example:\n"
                    "3 years of experience in Python, pandas, and scikit-learn. "
                    "BSc Computer Science. Built ML models for customer churn prediction. "
                    "Familiar with SQL, Tableau, and basic NLP."
                ),
                lines=6,
            )

            job_description = gr.Textbox(
                label="Job Description to Analyse (Optional — paste a specific job posting)",
                placeholder=(
                    "Paste the full text of a job posting you're interested in.\n"
                    "The Job Analyst will summarize it and the Career Advisor will score your fit.\n\n"
                    "If left empty, the agents will work with the job listings they find."
                ),
                lines=8,
            )

            with gr.Row():
                run_btn = gr.Button("🚀 Run Job Search", variant="primary", size="lg")
                clear_btn = gr.Button("🗑️ Clear", variant="secondary")

            output = gr.Markdown(
                label="Results",
                value="*Results will appear here after you run the search.*"
            )

            # Wire the button to the function
            run_btn.click(
                fn=run_search,
                inputs=[job_title, location, candidate_profile, job_description],
                outputs=output,
            )

            clear_btn.click(
                fn=lambda: ("", "", "", "", "*Results will appear here after you run the search.*"),
                outputs=[job_title, location, candidate_profile, job_description, output],
            )

        # ---- TAB 2: About / Architecture ---- #
        with gr.Tab("📚 About This Project"):
            gr.Markdown("""
## About This Application

This project is a **CrewAI-based multi-agent job search assistant**, built as an extension
of the original [job-search-assistant](https://github.com/arahmanmdmajid/job-search-assistant)
which used LangGraph.

---

## Architecture

### Agents
| Agent | Role | Tool |
|---|---|---|
| Job Market Researcher | Finds live job listings | Tavily Search API |
| Salary Analyst | Research compensation benchmarks | Remotive API |
| Job Description Analyst | Summarizes job postings | GPT-4o-mini (custom) |
| Career Advisor | Scores candidate-job fit | Resume Matcher (custom) |

### Workflow (Sequential Process)
```
Task 1: Research Jobs  →  Task 2: Salary Research
                       →  Task 3: Summarize Job Description
                       ↓  (all outputs combined)
                      Task 4: Match & Final Report
```

### Tools
- **Job Search Tool** — queries Tavily API for live listings
- **Salary Research Tool** — pulls compensation data from Remotive
- **Job Description Summarizer** — structured GPT-4o-mini summarization
- **Resume Matcher** *(custom)* — scores candidate fit 0-100 with strengths/gaps

### Fallback Handling
- API failures caught with try/except in every tool
- Crew retried up to 2 times before returning a friendly error message
- Empty/invalid outputs detected and handled gracefully

### Observability (Langfuse)
When Langfuse keys are configured, every agent execution, LLM call,
tool call, token count, and latency is automatically tracked at:
👉 [cloud.langfuse.com](https://cloud.langfuse.com)

---

## MCP (Model Context Protocol) Awareness

This project could benefit from MCP in the following ways:

**Tools that could be MCP servers:**
- The Tavily job search could be exposed as an MCP server so any agent
  or application can call it without re-implementing the API client
- The Remotive salary tool could be a standardised MCP data source
- A resume/CV parser could be an MCP server shared across projects

**Benefits of MCP here:**
- Tool definitions would be standardised (no duplicating `@tool` wrappers)
- New agents could discover and use tools dynamically
- The Resume Matcher could become a reusable MCP server for any career app

---

*Built with: CrewAI · OpenAI GPT-4o-mini · Tavily · Remotive · Langfuse · Gradio*
""")

    return demo


# ------------------------------------------------------------------ #
# Entry point
# ------------------------------------------------------------------ #
if __name__ == "__main__":
    demo = build_ui()
    demo.launch(
        server_name="0.0.0.0",
        server_port=7860,
        share=False,       # Set to True to get a public link
        show_error=True,
    )
